### ISSUE TITLE
Drop support for Python 2 (in next major version)

### ISSUE THREAD

**Issue by paulmelnikow** [lace/vg#111]
Python 2 is deprecated and will not be supported in future versions of vg. This will be marked as a breaking change.

**Comment by paulmelnikow** [comment]
Here's the sequence of things I'd like to do here:

- [x] Merge non-breaking changes (#159)
- [ ] Add major-version forward-compatibility layer (#158)
- [ ] Cut a 1.11.0 release and verify (at least in Python 3 🙄) that this is working.
- [ ] Drop support for Python 3 (#162)
- [ ] Migrate the build to Poetry (#161)
- [ ] Release 2.0.0rc1 and verify that it works.
- [ ] Release 2.0.0
